name: Keep Supabase Alive

on:
  schedule:
    # Berjalan otomatis setiap hari Senin dan Kamis jam 09:00 UTC (jam 16:00 WIB)
    - cron: '0 9 * * 1,4'
  workflow_dispatch: # Memungkinkan kamu untuk trigger manual kapan saja dari tab Actions

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase Database
        run: |
          curl -X GET "${{ secrets.SUPABASE_URL }}/rest/v1/profile?limit=1" \
          -H "apikey: ${{ secrets.SUPABASE_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_KEY }}"
